name: Update Motivos JSON

on:
  schedule:
    - cron: "*/15 * * * *" # Ejecuta cada 15 minutos
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  update-motivos:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Realizar la petición a la API
      - name: Fetch data from API
        id: fetch_api
        run: |
          API_URL="https://api.apico.dev/v1/80f030/1Ix-MDYTz3bLzql2HiMPnuKAOQd2B6tDEet2eGTu0R7g/values/Sheet1" # Cambia esto por tu URL
          curl -s "$API_URL" > motivos.json

      # 4. Subir los cambios (si hubo alguno)
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add motivos.json
          git commit -m "Update motivos.json [ci skip]"
          git push
