name: Update Motivos JSON

on:
  schedule:
    - cron: "*/10 * * * *" # Ejecuta cada 15 minutos
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  update-motivos:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Realizar la petición a la API
      - name: Fetch data from API
        id: fetch_api
        run: |
          API_URL="https://api.apico.dev/v1/80f030/1Ix-MDYTz3bLzql2HiMPnuKAOQd2B6tDEet2eGTu0R7g/values/Sheet1" # Cambia esto por tu URL
          curl -s "$API_URL" > motivos.json

      # 3. Confirmar si hubo algún cambio en `motivos.json`
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet motivos.json; then
            echo "No changes in motivos.json."
            echo "update=false" >> $GITHUB_ENV
          else
            echo "Changes detected in motivos.json."
            echo "update=true" >> $GITHUB_ENV
          fi

      # 4. Subir los cambios (si hubo alguno)
      - name: Commit and push changes
        if: env.update == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add motivos.json
          git commit -m "Update motivos.json [ci skip]"
          git push
